spring:
  application:
    name: server
  mail:
    host: smtp.free.fr
    port: 587
    username: thibaut.delorme@free.fr
    password: Jt04022009
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb+srv://thibautdelorme:Ot8zMb8IXM4xDdkG@smartbaticluster.ixarm.mongodb.net/?retryWrites=true&w=majority&appName=SmartBatiCluster
      database: smart_bati
